services:
  web:
    build:
      context: .
      dockerfile: .nixpacks/Dockerfile
    env_file:
      - .env
    ports:
      - "80:3000"
      - "3001:3001"
      - "443:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
