services:
  web:
    build:
      context: .
      dockerfile: .nixpacks/Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
