services:
  web:
    build:
      context: .
      dockerfile: .nixpacks/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
